### ISSUE TITLE
[Travis Plugin] Display builds in list

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage#4]
Mockups are here: https://whimsical.com/KnT9oFQGNGCcy5rhp8Rp2n

![mockup](https://user-images.githubusercontent.com/562403/88029970-92356e80-cb32-11ea-8460-418dbe69df55.png)

Some comments:

 1. The commit heading should link to that build in travis-ci.com
 2. The search should be client side only - it should filter on commit heading, commit sha and branch name.
 3. The two details are the length of time the build ran for, and the length of time ago that it ran.
 4. There is a refresh button in the top right corner of the table to refresh the list of builds.
 5. There should be pagination at the bottom

This page looks like this in Travis CI. My mockup attempts to stick pretty close to that.

![Screenshot 2020-07-21 at 08 59 23](https://user-images.githubusercontent.com/562403/88030107-bb55ff00-cb32-11ea-9236-6026dda80639.png)

The empty state of the list can simply explain to the user that there are no builds.

![Screenshot 2020-07-21 at 09 04 36](https://user-images.githubusercontent.com/562403/88030129-c577fd80-cb32-11ea-99ad-83df9919cd89.png)

When a HTTP error occurs, it can be displayed near the top of the page just like the Circle CI plugin does.

![Screenshot 2020-07-21 at 09 05 18 (1)](https://user-images.githubusercontent.com/562403/88030195-d9236400-cb32-11ea-8a5b-6928c385c492.png)

# TODO

- [x] Show a basic list of builds in the UI with the information described in the mockup above.
- [x] In a settings dialog, allow the user to specify their API token and the project they wish to view.
- [x] Enable the build retry functionality. Clicking the icon on the right side of each build should re-run that build.
- [x] Enable pagination
- [x] Enable searching by commit heading, commit sha and branch name

**Comment by zenway-js** [comment]
I think this one is ready

**Comment by dtuite** [comment]
Looks good. There are two small issues I noticed but I will comment on the PR.
